[package]
name = "sg-tree-rust"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <youremail@example.com>"]
description = "A Semantic Graph Tree (SG-Tree) implementation in Rust with Redb persistence and BERT-based embeddings."
license = "MIT"
repository = "https://github.com/yourusername/sg-tree-rust"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
sha2 = "0.10"
parking_lot = "0.12"
rayon = "1.5"
salvo = { version = "0.38", features = ["tokio"] }
candle = { version = "0.4", features = ["cuda", "safetensors"] }
candle-transformers = "0.4"
hf-hub = "0.5"
rand = "0.8"
redb = "0.5"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
